config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#welcome'
  resources :categories do
    get 'new_spending', to: 'categories#new_spending'
    post 'new_spending', to:
    'categories#create_spending'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :icon, presence: true
  belongs_to :user
  has_many :category_spendings
  has_many :spendings, through: :category_spendings
  mount_uploader :icon, IconUploader
end

app/models/category_spending.rb
class CategorySpending < ApplicationRecord
  belongs_to :category
  belongs_to :spending
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :user, foreign_key: :author_id, class_name: 'User'
  has_many :category_spendings
  has_many :categories, through: :category_spendings

  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :spendings, foreign_key: :author_id, dependent: :destroy
  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :total_spent_calculator
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end

  def total_spent_calculator(id)
    @category = Category.find(id)
    @total_spent = @category.spendings.reduce(0) do |acc, spending|
      acc + spending.amount
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def new_spending
    @category = Category.find(params[:category_id])
    @spending = Spending.new
    @categories = current_user.categories
  end

  def create_spending
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
    spending = Spending.new(spending_params)
    if current_user.spendings << spending
      category_spending = CategorySpending.new(category_id: params[:selected_category_id], spending_id: spending.id)

      if category_spending.save
        flash[:notice] = 'Spending created successfully'
        redirect_to category_path(params[:selected_category_id])

      else
        flash.now[:alert] = 'Something went wrong'
        render :new_spending
      end

    else
      flash.now[:alert] = 'Something went wrong'
      render :new_spending
    end
  end

  def show
    @category = Category.find(params[:id])
    @spendings = @category.spendings.reverse
    total_spent_calculator(params[:id])
  end

  def create
    category = Category.new(category_params)

    if current_user.categories << category

      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      flash.now[:alert] = 'Please check your input and try again!'
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def spending_params
    params.require(:spending).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:welcome]
  def welcome
    return unless current_user

    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_button_category_spendings.html.erb
<div class="container-fluid">
    <div class="row fixed-bottom btn-welcome">
        <div class="full-width-button-container btn btn-success-category">
            <% if request.path == categories_path %>
              <%= button_to "Create New Category",  new_category_path,class:"btn-categories-add btn-success-category", method: :get %>
            <% else %>
                <%= button_to "Create New Transaction",  category_new_spending_path(category_id: @category.id),class:"btn-categories-add btn-success-category", method: :get %>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<div class="card text-bg-light mb-4 mt-3 mx-auto d-flex flex-row" style="width: 23rem;">
    <%= image_tag(category.icon.url, class:"card-img-top img_container") if category.icon? %>
  <div class="card-body">
    <h5 class="card-title"><%= category.name %></h5>
  </div>
  <div class="card-body d-flex justify-content-end">
    <% if request.path != "/categories/#{category.id}" %>
     <h5 class="card-title">Transactions: $<%= total_spent_calculator(category.id) %></h5>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% if current_user %>
      <%= render "layouts/navigation"%>
        <div class="jumbotron text-center mt-5">
            <h1 class="display-4">Welcome <%= current_user.name %></h1>
            <p class="lead">You can manage your budget from your cell phone.</p>
            <hr class="my-4">
        </div>
<% end %>

<div class="mb-4">
<% @categories.each do |category| %>
    <a href="/categories/<%= category.id %>", id ="category_<%= category.id %>">
        <%= render category%>
    </a>
<% end %>
</div>



<%= render "categories/button_category_spendings"%>

app/views/categories/new.html.erb
<%= render "layouts/navigation"%>

<%= form_with model: @category, url: categories_path, class: "mt-4", method: :post do |f| %>
    <div class="mb-3">
        <%= f.text_field :name, class: "form-control", placeholder: "Name"%>
    </div>
    

    <div class="mb-3">
        <%= f.file_field :icon, accept: 'image/jpeg,image/gif,image/png', class: "btn btn-sm btn-light", value: "Choose Icon" %>
        <%= f.submit "Add category", class: "btn btn-success" %>
    </div>

<% end %>

app/views/categories/new_spending.html.erb
<%= render "spendings/spending_nav"%>


<%= form_with model: @spending, url: category_new_spending_path, class: "mt-4", method: :post do |f| %>
    <div class="mb-3">
        <%= f.text_field :name, class: "form-control", placeholder: "Name", requried: true %>
    </div>
    
    <div class="mb-3">
        <%= f.number_field :amount, class: "form-control", placeholder: "Amount", requried: true %>
    </div>

     <select class="form-select" aria-label="Default select example" name="selected_category_id">
            <option selected>Select category</option>
            <% @categories.each do |category| %>
                <option value="<%= category.id %>"><%= category.name %></option>
            <% end %> 
    </select>

    <div class="mb-3 d-flex mt-3 justify-content-center">
        <%= f.submit "Add Transaction", class: "btn btn-success" %>
    </div>

<% end %>

app/views/categories/show.html.erb
<%= render "spendings/spending_nav"%>


<div class="card text-bg-warning mb-4 mt-3 mx-auto d-flex flex-row" style="width: 21rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @category.name %></h5>
  </div>
  <div class="card-body d-flex justify-content-end">
     <h5 class="card-title">Total Spent: $<%= @total_spent %></h5>
  </div>
</div>

<%= render @spendings %>



<%= render "categories/button_category_spendings"%>

app/views/layouts/_messages.html.erb
<% if alert %>
    <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

<% if notice %>
    <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar text-white">
  <div class="container-fluid">
    <%= link_to "", root_path, class: "fa-solid fa-arrow-left smaller-heading btn-login", title: "Back"%>
    </button>
    <div class="nav-item-cat">
          <%= link_to "Logout", destroy_user_session_path, class: "nav-link-cat text-white ", data: { turbo_method: :delete }%>
        </div>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-white">
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, class: "nav-link text-white ", data: { turbo_method: :delete }%>
        </li>

        <li class="nav-item">
          <%= link_to "", root_path, class: "bi bi-arrow-left smaller-heading btn-login fa-2x"%>
        </li>
      </ul>
    </div>
    <% if request.path == categories_path %>
      <a class="navbar-brand text-white" href="#">CATEGORIES</a>
      <a class="navbar-brand" href="#">
      <i class="bi bi-search text-white"></i>
    </a>
      <% elsif request.path == new_category_path %>
        <a class="navbar-brand text-white" href="#">New category</a>
        <%= link_to "Logout", destroy_user_session_path, class: "nav-link text-white", data: { turbo_method: :delete }%>
      <% else %>
      <a class="navbar-brand text-white" href="#">TRANSACTIONS</a>
      <%= link_to "Logout", destroy_user_session_path, class: "nav-link text-white", data: { turbo_method: :delete }%>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Add Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Font Awesome CSS (you may need to adjust the paths) -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">

  </head>

  <body>
  <%= render "layouts/messages"%>
    <%= yield %>
  </body>
</html>

app/views/spendings/_spending.html.erb
<div class="card text-bg-light mb-4 mt-3 mx-auto d-flex flex-row" style="width: 21rem;">
  <div class="card-body">
    <p class="card-title"><strong>Name:</strong> <%= spending.name %></p>
  </div>
  <div class="card-body d-flex justify-content-end">
     <p class="card-title"><strong>Spent:</strong> $<%= spending.amount %></p>
  </div>
</div>

app/views/spendings/_spending_nav.html.erb
<head>
    <nav>
        <ul class="items_container">
            <li class="nav_items">
                <% if request.path == category_new_spending_path(category_id: @category.id) %>
                    <%= link_to "", category_path(@category.id), class: "fa-solid fa-arrow-left smaller-heading btn-login"%>
                <% else %>
                <%= link_to "", root_path, class: "fa-solid fa-arrow-left smaller-heading btn-login", title: "Back"%>
                <% end %>
            </li>
            <% if request.path != new_category_path %>
                <li class="nav_items">
                    TRANSACTIONS
                </li>
            <% else %>
                <li class="nav_items">
                Create Category
                </li>
            <% end %>
            
            <li class="nav_items">
                <%= link_to "Logout", destroy_user_session_path, class: "nav-items-cat text-white ", data: { turbo_method: :delete }%>
            </li>
        </ul>
      </nav>
</head>

app/views/users/welcome.html.erb
<div class="container-fluid mb-4">
    <div class="row">
        <div class="col-12 center-text">
            <h1>Budget App</h1>
        </div>
    </div>
    <div class="row fixed-bottom btn-welcome mb-1">
        <div class="full-width-button-container">
            <%= button_to "LOG IN", new_user_session_path,class:"full-width-button btn-1" %>
        </div>
        <div class="full-width-button-container">
            <%= button_to "SIGN UP", new_user_registration_path,class:"full-width-button btn-2", method: :get %>
        </div>
    </div>
</div>